feat(exchange): emphase on the filter button
Serkels/serkels.eu pull request #1720
Opened 2024-08-21 09:28 UTC by JNSPK

<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/kKdbm7emfVgYNTT2sG/giphy.gif?cid=790b7611guvj0iq6f539papqaf5yk4bmue7w5x3f0lwprki9&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1695 </p>

2024-08-21 11:41 UTC, douglasduteil requested changes
<p align="center">
    <img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnFqdzZ6aXM1MTk3cnp5aWVmeGZ6Nm02cjI1MWsxNzNyaHMwMDdsbSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xTiQyBOIQe5cgiyUPS/giphy.gif">
</p>

2024-08-21 11:41 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +        })} bg-secondary hover:bg-secondary`}
Prefer 
```tsx
className={button({
  active: filter_query === filter_params_schema.enum.SUCCESS,
  intent: "secondary"
})}
```

2024-08-21 11:41 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +        className={`${button({
Prefer 
```tsx
className={button({
  active: filter_query === filter_params_schema.enum.SUCCESS,
  intent: "primary"
})}
```

2024-08-21 11:41 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +      className: "w-1/2 whitespace-nowrap",
```suggestion
      className: "w-1/2 whitespace-nowrap",
```

Can you find another way ? The button is an inline-block right ?

2024-08-21 11:41 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +        button: "hover:bg-secondary",
```suggestion
```

Seems unused

2024-08-22 13:35 UTC, JNSPK commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +        })} bg-secondary hover:bg-secondary`}
Done. Does it suits you ?

2024-08-22 13:35 UTC, JNSPK commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +        className={`${button({
Done. Does it suits you ?

2024-08-22 13:35 UTC, JNSPK commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +      className: "w-1/2 whitespace-nowrap",
Flex-1 Done. Does it suits you ?
#FLEXFORLIFE

2024-08-22 13:36 UTC, JNSPK commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
> +        button: "hover:bg-secondary",
True that ! Done.

2024-08-26 01:16 UTC, merged