feat(exchange):display placeholder
Serkels/serkels.eu pull request #1755
Opened 2024-08-27 10:39 UTC by JNSPK

<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/10xp3IDPPOG1OM/giphy.gif?cid=790b7611njlhwxujw4kygf7mznwtj0apg0da5ryg7qwx38oa&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1708 </p>

2024-08-30 16:41 UTC, douglasduteil requested changes

2024-08-30 16:41 UTC, douglasduteil commented on packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
> +            onChange={() => setValue("return_id", "Dans quelle catégorie ?")}
The return_id should be a category id !

2024-08-30 16:41 UTC, douglasduteil commented on packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
> -        required={has_return}
Why removing the requirements?

2024-09-02 14:35 UTC, JNSPK commented on packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
> -        required={has_return}
Because if has_return is true, the select is hidden so it is implicit that the field is required when has_return is true. 

Or maybe i'm a crazy guy :D

2024-09-02 14:52 UTC, JNSPK commented on packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
> +            onChange={() => setValue("return_id", "Dans quelle catégorie ?")}
This is only for placeholder purposes. 
It will take the value of a category as select is required .
I cannot put any placeholder otherwise. Or i'm a stupiiiiiiiiiiid guy (it can be).

2024-09-03 23:27 UTC, douglasduteil approved these changes

2024-09-03 23:32 UTC, merged